many copy-diffs{,-test,-script} improvements
- timestamps on many log statements
- remove untracked files that are not / no longer present in the source
  repo
- remove files under .git in the destination that are not present in the
  source repo’s .git
  - this, for example, clears out deleted branch refs from the
    destination repo
- fire on changes to untracked (but not .gitignore’d) files; complete
  treating untracked-but-not-gitignored files as 1st-class citizens when
  copy-diff’ing
- verify that some commands give equal output on the source and dest
  repos when `copy-diffs` is finished:
  - git diff
  - git diff —cached
  - git lso  # list untracked files
- handle the situation where `watchman` was started without the $USER’s
  full $PATH, e.g. by `launchd` on OSX.

diff --git a/watchman/copy-diffs-script b/watchman/copy-diffs-script
--- a/watchman/copy-diffs-script
+++ b/watchman/copy-diffs-script
@@ -3,23 +3,42 @@
 mirror_remote="$1"
 shift
 
-echo "*** $(date +%Y-%m-%d-%H:%M:%S) $PWD: remote $mirror_remote, found changed files: $@"
+dt() {
+   date +%Y-%m-%d-%H:%M:%S
+}
 
-git_files="$(git ls-files "$@")"
+log() {
+   echo "*** $(dt) $PWD: $@"
+}
+
+log "remote $mirror_remote, watchman found changed paths: $@"
+
+filter_files() {
+   for file in "$@"; do
+      if [ ! -d "$file" ] && ! git check-ignore "$file" &> /dev/null && [ "$file" != ".git/index.lock" ]; then
+         echo "$file"
+      fi
+   done
+}
+git_files=$(filter_files "$@")
+
+if [ -z "$GIT_HELPERS_HOME" ]; then
+   source .git-rc
+fi
+
+set -e
 
 copy_files() {
-   echo "Copying: $git_files"
-   g cd "$mirror_remote"
+   git command-exists copy-diffs
+   if ! git copy-diffs "$mirror_remote"; then
+     log "** Failed!"
+   fi
+   log "Done"
 }
 
 if [ -n "$git_files" ]; then
+   log "Found changed files: $git_files"
    copy_files
 else
-   for arg in "$@"; do
-      if [ "$arg" == ".git/index" ]; then
-         copy_files
-         exit $?
-      fi
-   done
-   echo "Skipping"
+   log "Skipping"
 fi
