lots of updates

diff --git a/rebase/git-original-commit b/rebase/git-original-commit
--- a/rebase/git-original-commit
+++ b/rebase/git-original-commit
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
 
 # Print the SHA of the commit that is currently being applied, during a rebase.
-cat .git/rebase-apply/original-commit
+if [ -f .git/rebase-apply/orig-commit ]; then
+	cat .git/rebase-apply/orig-commit
+elif [ -f .git/rebase-merge/orig-commit ]; then
+	cat .git/rebase-merge/orig-commit
+else
+	echo "Error: couldn't find .git/rebase-{merge,apply}/orig-commit" >&2
+	exit 1
+fi
